name: Windows MSVC Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Install Clang-tools via Chocolatey
      - name: Install Clang tools
        run: choco install -y llvm

      # Run clang-format to check formatting
      - name: Check formatting with clang-format
        run: |
          Get-ChildItem -Recurse -Include *.h, *.cpp, *.hpp | ForEach-Object {
            clang-format --Werror --dry-run --style=file $_.FullName
          }
        shell: pwsh

      # Configure CMake with MSVC generator and export compile commands
      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }}
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_C_COMPILER=cl
          -G "Visual Studio 17 2022"

      # Run clang-tidy for static analysis
      - name: Run clang-tidy
        run: |
          $build_dir = "${{ github.workspace }}/build"
          run-clang-tidy.py -p $build_dir -header-filter=".*"
        shell: python

      # Build the project
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release

      # Run tests
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --build-config Release
