name: Windows MSVC Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Configure CMake with MSVC generator and export compile commands
      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }}
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_C_COMPILER=cl
          -G "Visual Studio 17 2022"
          -DCMAKE_BUILD_TYPE=Release

      # Build the project
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release

      # Run tests
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --build-config Release
